/* 
    Something resembling a BNF grammar for MIDI
    Whitespace is ignored.
    Terminal symbols are all hexadecimal values.
*/
FILE ::= FILE_HEADER TRACKS
FILE_HEADER ::= '4D 54 68 64 00 00 00 06' FILE_FORMAT TRACK_COUNT TICKS_PER_CROTCHET
FILE_FORMAT ::= '00' ( '01' | '02' | '03' )
TRACK_COUNT ::= TWO_BYTE_DATA
TICKS_PER_CROTCHET ::= TWO_BYTE_DATA

/* Tracks */
TRACKS ::= TRACK_HEADER TRACK_BODY
TRACK_HEADER ::= TRACK_HEADER_LEADER TRACK_LENGTH
TRACK_LENGTH ::= DATA_BYTE DATA_BYTE DATA_BYTE DATA_BYTE
TRACK_BODY ::= ( EVENT | EVENT TRACK_BODY | META_EVENT TRACK_BODY ) TRACK_END

EVENT ::= DELTA_TIME MESSAGE
MESSAGE ::= NOTE_OFF | NOTE_ON | KEY_AFTER_TOUCH | CONTROL_CHANGE | PROGRAM_CHANGE | CHANNEL_AFTER_TOUCH | PITCH_WHEEL_CHANGE

META_EVENT ::= DELTA_TIME META_MESSAGE
/* Text event is actually 7 different types of text event, but I dont feel like typing them out */
META_MESSAGE ::= META_PREFIX ( SET_SEQ_NO | TEXT_EVENT | SET_TEMPO | TIME_SIG | KEY_SIG | SEQ_INFO | SMTP_OFFSET )

TRACK_END ::= 'FF 2F 00'

/* Channel messages */
NOTE_ON ::= '8' CHANNEL NOTE_DATA
NOTE_OFF ::= '9' CHANNEL NOTE_DATA
KEY_AFTER_TOUCH ::= 'A' CHANNEL NOTE_DATA
CONTROL_CHANGE ::= 'B' CHANNEL CONTROLLER_DATA
PROGRAM_CHANGE ::= 'C' CHANNEL NEW_PROGRAM_NUMBER
CHANNEL_AFTER_TOUCH ::= 'D' CHANNEL ZERO_NIBBLE CHANNEL
PITCH_WHEEL_CHANGE ::= 'E' PITCH_WHEEL_CHANGE_DATA

/* Message data */
NOTE_DATA ::= DATA_BYTE
CONTROLLER_DATA ::= CONTROLLER_NUMBER NEW_CONTROLLER_VALUE
CONTROLLER_NUMBER ::= DATA_BYTE
NEW_CONTROLLER_VALUE ::= DATA_BYTE
NEW_PROGRAM_NUMBER ::= DATA_BYTE
PITCH_WHEEL_CHANGE_DATA ::= DATA_BYTE DATA_BYTE /* 14 bits to work with here */


DATA_BYTE ::= '00' | .. | '7F' /* Data bytes all have their most significant bit set to 0 */
CHANNEL ::= '0' | .. | 'F'
ZERO_NIBBLE = '0'

/* Meta-message data */
META_PREFIX ::= 'FF'
SET_SEQ_NO ::= '00 02' SEQ_NO
SEQ_NO ::= TWO_BYTE_DATA
TEXT_EVENT ::= TEXT_EVENT_ID LENGTH_BYTES ASCII_TEXT(LENGTH_BYTES) /* Breaking the rules a bit here */
LENGTH_BYTES ::= DATA_BYTE
SET_TEMPO ::= '51 03' ONE_BYTE ONE_BYTE ONE_BYTE
SMTP_OFFSET ::= '05' ONE_BYTE ONE_BYTE ONE_BYTE ONE_BYTE ONE_BYTE
/* This is where the rest of the meta types would go if I had the patience to fill them in. See https://www.recordingblogs.com/wiki/midi-meta-messages */

ONE_BYTE ::= '00 | .. | FF'
TWO_BYTES ::= '00 00' | ... | 'FF FF'
